export const GET_ERRORS = "GET_ERRORS";
export const GET_OPERATIONS = "GET_OPERATIONS";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_SOLDETOTAL = "GET_SOLDETOTAL";
export const SET_TOGGLE = "SET_TOGGLE";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_DEMANDE = "GET_DEMANDE";
export const DELETE_DEMANDE = "DELETE_DEMANDE";
export const DETAILS_DEMANDE = "DETAILS_DEMANDE";
// ONE PARAM
export const FETCH_DEMANDE = "FETCH_DEMANDE";
export const FETCH_DEMANDE_NUMERO_COMPTE = "FETCH_DEMANDE_NUMERO_COMPTE";
export const FETCH_DEMANDE_DATE_CREATION = "FETCH_DEMANDE_DATE_CRAETION";
export const FETCH_DEMANDE_STATUT = "FETCH_DEMANDE_STATUT";

// TWO PARAMS
export const FETCH_DEMANDE_MOTIF_STATUT = "FETCH_DEMANDE_MOTIF_STATUT";
export const FETCH_DEMANDE_MOTIF_DATE_CREATION =
  "FETCH_DEMANDE_MOTIF_DATE_CREATION";
export const FETCH_DEMANDE_NUMERO_COMPTE_STATUT =
  "FETCH_DEMANDE_NUMERO_COMPTE_STATUT";
export const FETCH_DEMANDE_STATUT_DATE_CREATION =
  "FETCH_DEMANDE_STATUT_DATE_CREATION";
export const FETCH_DEMANDE_NUMERO_COMPTE_DATE_CREATION =
  "FETCH_DEMANDE_NUMERO_COMPTE_DATE_CREATION";

export const FETCH_DEMANDE_NUMERO_COMPTE_MOTIF =
  "FETCH_DEMANDE_NUMERO_COMPTE_MOTIF";

// THREE PARAMS
export const FETCH_DEMANDE_NUMERO_COMPTE_MOTIF_STATUT =
  "FETCH_DEMANDE_NUMERO_COMPTE_MOTIF_STATUT";
export const FETCH_DEMANDE_MOTIF_STATUT_DATE_CREATION =
  "FETCH_DEMANDE_MOTIF_STATUT_DATE_CREATION";
export const FETCH_DEMANDE_NUMERO_COMPTE_MOTIF_DATE_CREATION =
  "FETCH_DEMANDE_NUMERO_COMPTE_MOTIF_DATE_CREATION";
export const FETCH_DEMANDE_NUMERO_COMPTE_STATUT_DATE_CREATION =
  "FETCH_DEMANDE_NUMERO_COMPTE_STATUT_DATE_CREATION";

//   ALL PARAMS

export const FETCH_DEMANDE_ALL_PARAMS = "FETCH_DEMANDE_ALL_PARAMS";

// LOGIN

export const SET_CURRENT_USER = "SET_CURRENT_USER";
